#!/bin/sh
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cp -r 0.isotherm 0

runApplication blockMesh

runApplication decomposePar

runParallel TEHDBoussinesqPimpleFoam


